#!/bin/bash

layout=$(setxkbmap -query | awk 'END{print $2}')
case $layout in
    us)
        setxkbmap ru
        ;;
    ru)
        setxkbmap us
        ;;
    cz)
        setxkbmap cz 
        ;;
    *)
        setxkbmap us
        ;;
esac
