#!/bin/bash

# Create file for putting output for lemon bar
panel_fifo="/tmp/i3_lemonbar_${USER}"

# Set geometru of bar
# geometry="x34"

# Set fonts
font="NotoSans-10"
iconfont="FontAwesome-11"

# Get resolution. Hardcoded =(
res_w=1366 # $(xrandr | grep "current" | awk '{print $8a}')

# --- APPLY XRES BEGIN
c_red_l="#fffb4934"
c_blue_l="#ff83a598"
c_blue_d="#ff458588"
c_magenta_d="#ffb16286"
c_black_d="#ff1d2021"
c_cyan_l="#ff8ec07c"
c_magenta_l="#ffd3869b"
c_yellow_l="#fffabd2f"
c_red_d="#ffcc241d"
c_background="#ff282828"
c_cyan_d="#ff689d6a"
c_green_l="#ffb8bb26"
c_foreground="#ffebdbb2"
c_white_d="#ffdbae93"
#       '': '',
c_green_d="#ff98971a"
c_yellow_d="#ffd79921"
c_cursor="#fffff000"
c_white_l="#fffbf1c7"
c_black_l="#ff665c54"
# --- APPLY XRES END

# color definitions 

# Dark
color_bgdark="$c_background"
color_bgdarkhl="$c_black_l"
color_fgdark="$c_black_l"

# Light
color_bglight="$c_white_l"
color_bglighthl="$c_white_d"
color_fglight="$c_foreground"

# Accent
color_accent1="$c_red_l"
color_accent1text="$c_black_l"

color_back="$color_bgdark"      # Default background
color_fore="$color_fglight"     # Default foreground
color_head="$color_bgdark"      # Background for unselected workspaces
color_wsp="$color_bgdarkhl"     # Background for selected workspace
color_icon="$color_fglight"     # For icons
color_clockbg="$color_bglight"  # Color for clock
color_clockfg="$color_fgdark"   # Color for clock

color_success="$c_green_l"           # Positive color for good times
color_warning="$c_yellow_l"           # Yellow color for warnings (eg, low battery)
color_critical="$c_red_l"          # Red color for critical meters

#default space between sections
stab='    '

# Char glyps for powerline fonts
sep_left=" "                        # Powerline separator left
sep_right=" "                       # Powerline separator right
sep_l_left=" "                      # Powerline light separator left
sep_l_right=" "                     # Powerline light sepatator right

# Icons
icon_bright="\uf185"
icon_battery="\uf0e7"
icon_clock="\uf017"                        # Clock icon
icon_calendar="\uf073"
icon_cpu="\uf0e4"                          # CPU icon
icon_globe="\uf0ac"                        # Globe icon
icon_home="\uf015"                         # Home icon (also linux)
icon_laptop="\uf109"                       # Laptop icon
icon_linux="\uf17c"                        # Linux (Tux) icon
icon_mail="\uf0e0"                         # Email icon
icon_mem="\uf0a0"                          # Memory icon
icon_music="\uf001"                        # Music icon
icon_paw="\uf1b0"                          # Paw icon
icon_prog="\uf108"                         # Window icon
icon_shell="\uf120"                        # Shell icon
icon_vol="\uf028"                          # Volume icon
icon_mute="\uf026"
icon_wsp="\uf108"                      # Workspace icon (paw duplicate for now)
icon_charging="\uf1e6"
icon_dl="\uf0ab"
icon_ul="\uf0aa"
icon_ssid="\uf1eb"
icon_share="\uf1e0"
icon_temp="\uf06d"			 # Fire
